{% set name = "algorecell_types" %}
{% set version = "9999" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - colomoto_jupyter
    - pydot
    - pandas

about:
  home: https://github.com/algorecell/algorecell_types
  summary: 'Generic types for reprogramming predictions from logical models'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

